sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_a6116f5786ba_key -iv $encrypted_a6116f5786ba_iv
    -in creds.json.enc -out creds.json
    -d
  - yarn install
script:
  - yarn test
  - yarn build
deploy:
  on: master
  provider: gcs
  project: $GCP_PRO
  access_key_id: $GCP_ACCESS_KEY_ID
  secret_access_key: $GCP_SECRET_KEY
  bucket: $GCP_BUCKET
  skip_cleanup: true
  local-dir: build
