language: node_js
node_js: node
cache: yarn
script:
  - yarn test
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: build
  script:
    - yarn deploy
  on:
    branch: master
