language: node_js
node_js: node
cache: yarn
script:
  - yarn test
  - yarn build
before_install:
  - openssl aes-256-cbc -K $encrypted_2fd045226a67_key -iv $encrypted_2fd045226a67_iv
    -in client-secret.json.enc -out client-secret.json -d
deploy:
  provider: gae
  keyfile: "client-secret.json.enc"
  project: "$PROJECT"
  on: master
