apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "personal-website-ingress-ip"
spec:
  backend:
    serviceName: web-service
    servicePort: 3000
